.once

; Memory Ranges ****************************************************************

.const mVRAM    = $80008000

; I/O Port Registers ***********************************************************

.const rIE0     = $00   
.const rIE1     = $01   
.const rIE2     = $02   
.const rIE3     = $03   
.const rIRQ0    = $04  
.const rIRQ1    = $05  
.const rIRQ2    = $06  
.const rIRQ3    = $07  
.const rSPD     = $08   
.const rDIV     = $10   
.const rTIMA    = $11  
.const rTMA     = $12   
.const rTAC     = $13   
.const rSB      = $20    
.const rSC      = $21    
.const rRP      = $24    
.const rNR10    = $30  
.const rNR11    = $31  
.const rNR12    = $32  
.const rNR13    = $33  
.const rNR14    = $34  
.const rNR21    = $39  
.const rNR22    = $3A  
.const rNR23    = $3B  
.const rNR24    = $3C  
.const rNR30    = $40  
.const rNR31    = $41  
.const rNR32    = $42  
.const rNR33    = $43  
.const rNR34    = $44  
.const rNR41    = $49  
.const rNR42    = $4A  
.const rNR43    = $4B  
.const rNR44    = $4C  
.const rNR50    = $50  
.const rNR51    = $51  
.const rNR52    = $52  
.const rPCM12   = $58 
.const rPCM34   = $59 
.const rLCDC    = $60  
.const rSTAT    = $61  
.const rSCY     = $62   
.const rSCX     = $63   
.const rWY      = $64    
.const rWX      = $65    
.const rLY      = $66    
.const rLYC     = $67   
.const rBGP     = $68   
.const rOBP0    = $69  
.const rOBP1    = $6A  
.const rBGPI    = $6B  
.const rBGPD    = $6C  
.const rOBPI    = $6D  
.const rOBPD    = $6E  
.const rPPUX    = $6F  
.const rODMAS   = $70 
.const rODMA1   = $71 
.const rODMA2   = $72 
.const rODMA3   = $73 
.const rVDMA0   = $74 
.const rVDMA1   = $75 
.const rVDMA2   = $76 
.const rVDMA3   = $77 
.const rVDMA4   = $78 
.const rVDMA5   = $79 
.const rVDMA6   = $7A 
.const rJOYP    = $90  

; Constants ********************************************************************


